<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net461</TargetFramework>
        <AssemblyTitle>COM3D25.i18nEx.Core</AssemblyTitle>
        <TargetName>$(AssemblyTitle)</TargetName>
        <AssemblyName>horse.coder.com3d25.tlcore</AssemblyName>
        <Product>COM3D25 i18nEx Core</Product>
        <RootNamespace>COM3D2.i18nEx.Core</RootNamespace>
        <DefineConstants>COM3D25;$(DefineConstants)</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <None Include="..\..\.editorconfig" Link=".editorconfig" />
        <Compile Include="..\..\COM3D2.i18nEx.Core\**\**\*.cs" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="BepInEx.Core" Version="5.4.16" />
        <PackageReference Include="ExIni" Version="1.0.2" IncludeAssets="compile" />
        <PackageReference Include="HarmonyX" Version="2.5.5" IncludeAssets="compile" />
        <PackageReference Include="UnityEngine.Modules" Version="2022.3.35" IncludeAssets="compile" />
        <PackageReference Include="COM3D2.GameLibs" Version="3.4*-*" IncludeAssets="compile" />
        <PackageReference Include="NETStandard.Library" Version="2.0.*" />
        <Reference Include="System.Windows.Forms" />
    </ItemGroup>
</Project>