<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net35</TargetFramework>
        <AssemblyTitle>COM3D2.i18nEx.TranslationExtract</AssemblyTitle>
        <TargetName>$(AssemblyTitle)</TargetName>
        <AssemblyName>horse.coder.com3d2.tlextract</AssemblyName>
        <Product>i18nEx for 2.x Translation Extractor</Product>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="..\..\COM3D2.i18nEx.TranslationExtract\**\*.cs"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="BepInEx.Core" Version="5.4.16"/>
        <PackageReference Include="UnityEngine.Modules" Version="5.6.0" IncludeAssets="compile"/>
        <PackageReference Include="COM3D2.GameLibs" Version="2.*-*" IncludeAssets="compile"/>
        <PackageReference Include="BepInEx.PluginInfoProps" Version="1.*"/>
    </ItemGroup>
</Project>